# Generated by Django 5.1.7 on 2025-03-18 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('text', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('health', 'Health'), ('sports', 'Sports'), ('education', 'Education'), ('business', 'Business')], default='tech', max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
